<a href="https://colab.research.google.com/github/peyyalakaushik21/data-analytics/blob/main/Kaushik.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#1.
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50])
print(np.ndim(arr1))
print(np.shape(arr1))
print(np.size(arr1))

1
(5,)
5


In [6]:
#2.
import numpy as np
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(arr2)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
#3.
arr_zeros_1d = np.zeros(5)
print(arr_zeros_1d)

arr_zeros_2d = np.zeros((3, 4))
print(arr_zeros_2d)

arr_zeros_3d = np.zeros((2, 3, 2))
print(arr_zeros_3d)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [107]:
#4.
import numpy as np
arr4 = np.ones((2,3))
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]]


In [108]:
#5.
import numpy as np
arr5 = np.full((2,3),7)
print(arr5)

[[7 7 7]
 [7 7 7]]


In [33]:
#6.
arr6 = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
print(np.random.choice(arr6))

arr62 = np.array([
    [0.1,0.2,0.3],
    [0.4,0.5,0.6]
])
print(np.random.shuffle(arr62))

0.5
None


In [41]:
#7.
arr7 = np.array([
    [10,11,12],
    [13,14,15],
    [48,49,50]
])
print(np.random.choice)

<bound method RandomState.choice of RandomState(MT19937) at 0x7BC3DAEC5F40>


In [42]:
#8.
arr8 = np.array([])

In [51]:
#9.
arr9 = np.array(["Red", "Blue", "Green", "Yellow", "Black"])
print(np.random.choice(arr9))

Red


In [112]:
#10.
arr10 = np.array([])

In [54]:
#11.
arr11 = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])
print(np.diff(arr11))

[5 5 5 5 5 5 5 5 5]


In [58]:
#12.
arr12 = np.array([10, 20, 30, 40, 50, 60])
print(np.abs(arr12))

[10 20 30 40 50 60]


In [64]:
#13.
arr13 = np.array([0,100])
print(np.linspace(arr13[0], arr13[1], num=6))

[  0.  20.  40.  60.  80. 100.]


In [67]:
#14.
arr14 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(np.ravel(arr14))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [74]:
#15.
arr15 = np.array([[1, 2, 3],[4, 5, 6]])
print(np.ravel(arr15))

[1 2 3 4 5 6]


In [89]:
#16.
arr16 = np.array([10, 20, 30, 40, 50])
arr16=arr16.astype("float")
print(np.dtype)

<class 'numpy.dtype'>


In [109]:
#17.
arr17 = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
print(np.shape(arr17))

(3, 3)


In [111]:
#18.
arr18 = np.array([10, 20, 30, 40, 50])
print(arr18.dtype)

int64


In [101]:
#19.
arr19 = np.array([45, 56, 67, 72, 81, 90, 95])
print(np.var(arr19))
print(np.std(arr19))
print(np.percentile==25)
print(np.percentile==75)
print(np.argmax(arr19))
print(np.argmin(arr19))
print(np.log10(arr19))


277.63265306122446
16.662312356369522
False
False
6
0
[1.65321251 1.74818803 1.8260748  1.8573325  1.90848502 1.95424251
 1.97772361]


In [106]:
#20.
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.array([7, 8, 9])
print(np.split(A, 3))
print(np.split(B, 3))
print(np.split(C, 3))

[array([1]), array([2]), array([3])]
[array([4]), array([5]), array([6])]
[array([7]), array([8]), array([9])]
