<a href="https://colab.research.google.com/github/peyyalakaushik21/data-analytics/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
numbers = np.array([1,2,3,4,5,6])
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr = np.array(["Ravi","Priya","Arun"])
print(arr.dtype)

<U5


In [ ]:
arr = np.array([10, 20, 30],dtype=float)
print(arr)
print(arr.dtype)

[10. 20. 30.]
float64


In [ ]:
import array as arr
arr = arr.array('i',[1,2,3])
print(arr)

array('i', [1, 2, 3])


In [ ]:
import numpy as np
arr = np.array([10, 20, 30],dtype='float')
print(arr)
print(arr.dtype)

[10. 20. 30.]
float64


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr.shape)

(5,)


In [ ]:
arr = np.arange(1, 10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.full(5,5)
print(arr)

[5 5 5 5 5]


In [ ]:
import numpy as np
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#1D
arr = np.ones(5)
print(arr)
#2D
arr = np.ones((2,3))
print(arr)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
new_arr = arr.reshape(2,3)
print(new_arr)
arr1 = np.arange(2,3)
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#identity matrix
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#random
arr = np.random.random(5)
print(arr)
#
arr1 = np.random.random((2,3))
print(arr1)

[0.08046097 0.21891854 0.85776953 0.51612876 0.37290307]
[[0.70826825 0.48671349 0.1287881 ]
 [0.87007562 0.11198873 0.78934338]]


In [ ]:
#uniform method(np.random.uniform(low, high, size))
arr3 = np.random.uniform(10, 50, 5)
print(arr3)


[48.68030531 42.50172086 43.89919446 11.60251483 47.44045547]


In [ ]:
#randn() Method
arr = np.random.randn(5)
print(arr)

#2D
arr2 = np.random.randn(2,3)
print(arr2)



[-2.25561485  1.10785583  0.96163625 -0.32656793 -0.34660043]
[[-0.92606948  1.72647266 -1.70742942]
 [-0.69770851  0.02870654 -1.36721595]]


In [ ]:
#choice() Method
arr = np.array([10,20,30,40,50])
result = np.random.choice(arr,5)
print(result)

names = ["Ravi","Priya","Arun","Ajay"]
result = np.random.choice(
    names,
    size=5,
    replace=True,
    p=[0.25, 0.25, 0.25, 0.25])
print(result)

[50 20 40 50 50]
['Priya' 'Ravi' 'Arun' 'Arun' 'Ajay']


In [ ]:
#seed
print(np.random.seed(10))
x = np.random.seed()
print(x)

None
None


In [ ]:
import numpy as np
num = np.random.randint(3, 10)
print(num)

5


In [ ]:
#Negative Values with Arange()
arr = np.array([10,20,30,40,50])
np.random.shuffle(arr)
print(arr)

[50 30 10 40 20]


In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60])
a = np.insert(arr,2,100)
print(a)

[ 10  20 100  30  40  50  60]


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])
a=np.delete(arr,[1,4,0,2])
print(a)

[40 60]


In [ ]:
import numpy as np
arr = np.array([
    [10,20,30],
    [30,40,50]])
result=np.insert(arr,1,[100, 200, 300],axis=0) #row wise insertion.
print(result)

[[ 10  20  30]
 [100 200 300]
 [ 30  40  50]]


In [ ]:
arr = np.array([
    [10,20],
    [30,40],
    [50,60]
])
result=np.insert(arr,1,[100, 200, 300],axis=1) #column wise insertion.
print(result)

[[ 10 100  20]
 [ 30 200  40]
 [ 50 300  60]]


In [ ]:
#Delete
result = np.delete(arr, 1, axis=0)
print(result)
result = np.delete(arr, 1, axis=1)
print(result)

[[10 20 30]]
[[10 30]
 [30 50]]


In [ ]:
import numpy as np
arr = ([10,20,30,40,50])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.std(arr))

150
10
50
30.0
14.142135623730951


In [ ]:
import numpy as np
arr = ([[10,20],
        [40,50]])
print(np.sum(arr,axis=0))
print(np.min(arr,axis=0))
print(np.max(arr,axis=0))
print(np.mean(arr,axis=0))
print(np.std(arr,axis=0))
print(np.average(arr,axis=0))
print(np.var(arr,axis=0))
print(np.percentile(arr,[10,20]))
print("________________________________")
print(np.sum(arr,axis=1))
print(np.min(arr,axis=1))
print(np.max(arr,axis=1))
print(np.mean(arr,axis=1))
print(np.std(arr,axis=1))
print(np.average(arr,axis=1))
print(np.var(arr,axis=1))
print(np.percentile(arr,[20,50]))

[50 70]
[10 20]
[40 50]
[25. 35.]
[15. 15.]
[25. 35.]
[225. 225.]
[13. 16.]
________________________________
[30 90]
[10 40]
[20 50]
[15. 45.]
[5. 5.]
[15. 45.]
[25. 25.]
[16. 30.]


In [ ]:
import numpy as np
arr2 = ([10,20,30,40,50,60])
print(np.quantile(arr,0.30))

19.0


In [ ]:
print(np.argmax(arr2))

5


In [ ]:
print(np.argmin(arr2))

0


In [ ]:
import numpy as np
arr3 = np.array([10,100,1000])
print(np.log10(arr3))

[1. 2. 3.]


In [ ]:
import numpy as np
arr3 = np.array([1,2,10])
print(np.log2(arr3))

[0.         1.         3.32192809]


In [ ]:
import numpy as np
arr4 = np.array([4,9,16,25])
print(np.sqrt(arr4))

[2. 3. 4. 5.]


In [ ]:
import numpy as np
arr5 = np.array([10.25, 20.67, 30.49])
print(np.round(arr5, 3))

[10.25 20.67 30.49]


In [ ]:
import numpy as np
arr6 = np.array([10.2, 10.8, 20.1])
print(np.floor(arr6))

[10. 10. 20.]


In [ ]:
import numpy as np
arr7 = np.array([10.2, 10.8, 20.1])
print(np.ceil(arr7))

[11. 11. 21.]


In [ ]:
import numpy as np
arr8 = np.array([-10, -5, 0, 5, 10])
print(np.abs(arr8))

[10  5  0  5 10]


In [ ]:
import numpy as np
arr9 = np.array([50, 10, 40, 20, 30])
result = np.sort(arr9) #Ascending order.
print(result)

[10 20 30 40 50]


In [ ]:
import numpy as np
arr9 = np.array([50, 10, 40, 20, 30])
result = np.sort(arr9)[::-1] #Descending order.
print(result)

[50 40 30 20 10]


In [ ]:
import numpy as np
result = np.array([50, 10, 40, 20, 30, 80, 90])
result = np.split(result, [0,2])
print(result)

[array([], dtype=int64), array([50, 10]), array([40, 20, 30, 80, 90])]


In [ ]:
arr = np.array([
    [10, 20],
    [30, 40],
    [50, 60],
    [70, 80]
])
print(np.split(arr,[4],axis=0))
print(np.split(arr,[0,1],axis=1))


[array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]]), array([], shape=(0, 2), dtype=int64)]
[array([], shape=(4, 0), dtype=int64), array([[10],
       [30],
       [50],
       [70]]), array([[20],
       [40],
       [60],
       [80]])]
